# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31980614f48a6b5b1e494eecc2a1c67586e5fe38d1db2910d5e56778c8eb55ee2b8482a91197bc35e7cf8d0198b010086a8cdcec6d63589d9bab6d0dad1d99bd

test:
  secret_key_base: 58b96f156e93738db76a35c5a6f73f6646b49b1176768f6e3e7977c25d5ab81d61b50f3c65dd73d283932ebbc97d0d2d1d8fe785bae1dea820567680ecb32954

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
